// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SentezMicro.Services.Customer.Customer.Persistence.Data;

namespace Customer.Persistence.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20211005081125_firstdb")]
    partial class firstdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SentezMicro.Services.Customer.Domain.Entities.ErpCustomer", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrentAccountAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAccountEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentAccountPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("InUse")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RecId");

                    b.ToTable("ErpCustomer");
                });
#pragma warning restore 612, 618
        }
    }
}
